### ISSUE TITLE
BIDS subject number lost in conversion to nnUNet dataset format

### ISSUE THREAD

**Issue by rohanbanerjee** [ivadomed/templates#10] opened 2023-04-13 16:38 UTC
## The issue
When we use this script to convert the dataset from BIDS to nnUNet (v2) format, the original subject name is changed into the nnUNet format like this for example: `sub-xxxR48 --> xxx_002_0000`. The issue with this is that the subject number in BIDS, which is 48 in the example, is not always equal to the id in the nnUNet dataset, which is 002 in the example. This makes it difficult to backtrack in subject specific issues.

## Potential solution
We can save an extra json/text file which can basically record the BIDS to nnUNet data mapping for subject-wise further analysis.

**Comment by naga-karthik** [comment] 2023-04-13 18:50
Thanks for raising this issue! I had this problem myself and I worked around it by saving the subject id and the session within the file name (for e.g. `tSCIZurichRaw_sub-zh05_ses-01_005_0000.nii.gz`, `tSCIZurichRaw_sub-zh66_ses-01_058_0000.nii.gz`, etc.). From what I understood, what nnUNet needs is the input files to be of the format `<task-name>_xxx_xxxx.nii.gz`. So, I basically updated the filename in [this line](https://github.com/ivadomed/templates/blob/main/dataset_conversion/convert_bids_to_nnunet.py#L196) to include the BIDS-wise subject and session as well as shown in the two examples above.

**Comment by naga-karthik** [comment] 2023-04-24 20:14
Closing this as it seems that the issue is resolved!

**Closed by naga-karthik** 2023-04-24 20:14 UTC
